conda_envs:
- name: base
  requirements: requirements.txt
dotfiles_configs:
  dotfiles_dir: C:\data\3_resources\20-29_workspace\20.02_win_dotfiles
  dotfiles_repo: ''
dotfiles_links:
- source: .bash_profile
  target: ~/.bash_profile
- source: .my_gitconfig
  target: ~/.my_gitconfig
- source: .gitignore_global
  target: ~/.gitignore_global
- source: .condarc
  target: ~/.condarc
- source: init.vim
  target: ~/AppData/Local/nvim/init.vim
- source: ginit.vim
  target: ~/AppData/Local/nvim/ginit.vim
- name: powershell_profile
  source: Microsoft.PowerShell_profile.ps1
  target: ~/onedrive_ezraameri/OneDrive - Microsoft/Documents/PowerShell/Microsoft.PowerShell_profile.ps1
- source: starship.lua
  target: ~/AppData/Local/clink/starship.lua
- source: starship.toml
  target: ~/.config\starship.toml
- source: config/vscode/vscode_settings.json
  target: ~/AppData/Roaming/Code/User/settings.json
- source: config/vscode/vscode_css_style.css
  target: ~/AppData/Roaming/Code/User/vscode_css_style.css
- source: winterminal.json
  target: ~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
- source: config/obsidian
  target: C:/data/3_resources/20-29_workspace/20.01_my_wiki/.obsidian
git_global_config:
- name: core.repositoryformatversion
  path: ~/.gitconfig
  state: absent
  value: 0
- name: core.filemode
  path: ~/.gitconfig
  state: absent
  value: 'false'
- name: core.bare
  path: ~/.gitconfig
  state: absent
  value: 'false'
- name: core.logallrefupdates
  path: ~/.gitconfig
  state: absent
  value: 'false'
- name: include.path
  path: ~/.gitconfig
  state: present
  value: ~/.my_gitconfig
- name: core.excludesfile
  path: ~/.my_gitconfig
  state: present
  value: ~/.gitignore_global
- name: core.longpaths
  path: ~/.my_gitconfig
  state: present
  value: 'true'
- name: core.useBuiltInFSMonitor
  path: ~/.my_gitconfig
  state: present
  value: 'false'
- name: core.autocrlf
  path: ~/.my_gitconfig
  state: present
  value: 'false'
- name: core.editor
  path: ~/.my_gitconfig
  state: present
  value: nvim
- name: pull.rebase
  path: ~/.my_gitconfig
  state: present
  value: 'false'
- name: fetch.prune
  path: ~/.my_gitconfig
  state: present
  value: 'false'
- name: rebase.autoStash
  path: ~/.my_gitconfig
  state: present
  value: 'false'
- name: rebase.instructionFormat
  path: ~/.my_gitconfig
  state: present
  value: '[%s], %an@%as'
- name: diff.guitool
  path: ~/.my_gitconfig
  state: present
  value: vscode
- name: diff.tool
  path: ~/.my_gitconfig
  state: present
  value: vscode
- name: merge.guitool
  path: ~/.my_gitconfig
  state: present
  value: vscode
- name: merge.tool
  path: ~/.my_gitconfig
  state: present
  value: vscode
- name: difftool.vscode.cmd
  path: ~/.my_gitconfig
  state: present
  value: code --wait --diff "$LOCAL" "$REMOTE"
- name: mergetool.vscode.cmd
  path: ~/.my_gitconfig
  state: present
  value: code --wait "$MERGED"
- name: filter.lfs.clean
  path: ~/.my_gitconfig
  state: present
  value: git-lfs clean -- %f
- name: filter.lfs.smudge
  path: ~/.my_gitconfig
  state: present
  value: git-lfs smudge -- %f
- name: filter.lfs.process
  path: ~/.my_gitconfig
  state: present
  value: git-lfs filter-process
- name: filter.lfs.required
  path: ~/.my_gitconfig
  state: present
  value: 'true'
- name: credential.helper
  path: ~/.my_gitconfig
  state: present
  value: manager
- name: credential.azreposCredentialType
  path: ~/.my_gitconfig
  state: present
  value: oauth
- name: credential.helperselector.selected
  path: ~/.my_gitconfig
  state: present
  value: manager
- name: credential.https://github.com.username
  path: ~/.gitconfig_personal
  state: present
  value: wameri
- name: core.repositoryformatversion
  path: ~/.my_gitconfig
  state: absent
  value: 0
- name: core.filemode
  path: ~/.my_gitconfig
  state: absent
  value: 'false'
- name: core.bare
  path: ~/.my_gitconfig
  state: absent
  value: 'false'
- name: core.logallrefupdates
  path: ~/.my_gitconfig
  state: absent
  value: 'false'
git_global_config_paths:
- ~/.my_gitconfig
- ~/.gitconfig
scoop_buckets:
- name: nerd-fonts
  state: install
- name: extras
  state: install
scoop_packages:
- name: Ffmpeg
  state: install
- name: Ninja
  state: install
- name: innounp
  state: install
- name: dark
  state: install
- name: 0xProto-NF
  state: install
- name: 3270-NF
  state: install
- name: Agave-NF
  state: install
- name: AnonymicePro-NF
  state: install
- name: Arimo-NF
  state: install
- name: AurulentSansMono-NF
  state: install
- name: BigBlueTerminal-NF
  state: install
- name: BitstreamVeraSansMono-NF
  state: install
- name: BlexMono-NF
  state: install
- name: CascadiaCode-NF
  state: install
- name: CascadiaMono-NF
  state: install
- name: CodeNewRoman-NF
  state: install
- name: ComicShannsMono-NF
  state: install
- name: CommitMono-NF
  state: install
- name: Cousine-NF
  state: install
- name: D2Coding-NF
  state: install
- name: DaddyTimeMono-NF
  state: install
- name: DejaVuSansMono-NF
  state: install
- name: DepartureMono-NF
  state: install
- name: DroidSansMono-NF
  state: install
- name: EnvyCodeR-NF
  state: install
- name: FantasqueSansMono-NF
  state: install
- name: FiraCode
  state: install
- name: FiraCode-NF
  state: install
- name: FiraMono
  state: install
- name: FiraMono-NF
  state: install
- name: GeistMono-NF
  state: install
- name: GoMono-NF
  state: install
- name: Gohu-NF
  state: install
- name: Hack
  state: install
- name: Hack-NF
  state: install
- name: HackGen-NF
  state: install
- name: Hasklug-NF
  state: install
- name: HeavyData-NF
  state: install
- name: Hurmit-NF
  state: install
- name: iA-Writer-NF
  state: install
- name: InconsolataGo-NF
  state: install
- name: InconsolataLGC-NF
  state: install
- name: Inconsolata-NF
  state: install
- name: IntelOneMono-NF
  state: install
- name: Iosevka
  state: install
- name: Iosevka-NF
  state: install
- name: Iosevka-Slab
  state: install
- name: IosevkaTerm-NF
  state: install
- name: IosevkaTermSlab-NF
  state: install
- name: JetBrainsMono-NF
  state: install
- name: Lekton-NF
  state: install
- name: LiberationMono-NF
  state: install
- name: Lilex-NF
  state: install
- name: MPlus-NF
  state: install
- name: MartianMono-NF
  state: install
- name: Meslo-NF
  state: install
- name: Monaspace-NF
  state: install
- name: Monocraft-NF
  state: install
- name: Monofur-NF
  state: install
- name: Monoid-NF
  state: install
- name: Mononoki-NF
  state: install
- name: Noto-NF
  state: install
- name: OpenDyslexic-NF
  state: install
- name: Overpass-NF
  state: install
- name: ProFont-NF
  state: install
- name: ProggyClean-NF
  state: install
- name: RecursiveMono-NF
  state: install
- name: RobotoMono-NF
  state: install
- name: SourceCodePro-NF
  state: install
- name: ShareTechMono-NF
  state: install
- name: SpaceMono-NF
  state: install
- name: NerdFontsSymbolsOnly
  state: install
- name: Terminus-NF
  state: install
- name: Tinos-NF
  state: install
- name: UbuntuMono-NF
  state: install
- name: Ubuntu-NF
  state: install
- name: UbuntuSans-NF
  state: install
- name: VictorMono-NF
  state: install
- name: ZedMono-NF
  state: install
vscode_extensions:
- a5hk.paper
- aaronthomas.vscode-snazzy-operator
- adpyke.codesnap
- akamud.vscode-theme-onedark
- akamud.vscode-theme-onelight
- alexandernanberg.horizon-theme-vscode
- alexdauenhauer.catppuccin-noctis
- andrewmarkle.primer-light
- anthropic.claude-code
- asvetliakov.vscode-neovim
- ban.spellright
- bat67.leetcode-extension-pack
- be5invis.vscode-custom-css
- benbusby.earthbound-themes
- bencoleman.armview
- bierner.markdown-mermaid
- bubersson.theme-hop-light
- catppuccin.catppuccin-vsc
- catppuccin.catppuccin-vsc-icons
- catppuccin.catppuccin-vsc-pack
- chrisjsewell.myst-tml-syntax
- cimpeanandrei.linux-terminal-flat
- cometeer.spacemacs
- connieth.bubblegum
- cs128.cs128-clang-tidy
- cschlosser.doxdocgen
- ctrlplusb.i-minimal-theme
- davidanson.vscode-markdownlint
- davidbwaters.macos-modern-theme
- devcenter.ms-devbox
- divyanshuagrawal.competitive-programming-helper
- docker.docker
- donjayamanne.githistory
- donjayamanne.kusto
- dracula-theme.theme-dracula
- eamodio.gitlens
- easyaspi314.macos-theme
- emilast.logfilehighlighter
- enkia.tokyo-night
- evan-buss.font-switcher
- fabiospampinato.vscode-highlight
- fcunhaneto.karry-color-golang-theme
- fehey.brackets-light-pro
- felicio.vscode-fold
- felipe-mendes.slack-theme
- fgcintra.longsight-light-theme
- formulahendry.code-runner
- gera2ld.markmap-vscode
- github.copilot
- github.copilot-chat
- github.github-vscode-theme
- goessner.mdmath
- grapecity.gc-excelviewer
- guyutongxue.cpp-reference
- harryhopkinson.vim-theme
- hellotham.vsc-rosely-light
- heron.firefox-devtools-theme
- heyitschun.ghibli-syntax-themes
- huacnlee.theme-macos-classic
- huynhduong.nvtokyo-theme
- iwyvi.chinolor
- jdinhlife.gruvbox
- jebbs.markdown-extended
- jeff-hykin.better-cpp-syntax
- josetr.cmake-language-support-vscode
- jprestidge.theme-material-theme
- kevinrose.vsc-python-indent
- leetcode.vscode-leetcode
- lextudio.restructuredtext
- liviuschera.noctis
- lninl.theme-hbuilderx-soft-green-light
- loilo.snazzy-light
- lumiknit.parchment
- meezilla.json
- metaphore.kanagawa-vscode-color-theme
- mhutchie.git-graph
- mike-flanigan.daobeam
- mikestead.dotenv
- momosct.momotheme
- ms-azure-devops.azure-pipelines
- ms-azure-load-testing.microsoft-testing
- ms-azuretools.azure-dev
- ms-azuretools.vscode-azure-github-copilot
- ms-azuretools.vscode-azure-mcp-server
- ms-azuretools.vscode-azureappservice
- ms-azuretools.vscode-azurecontainerapps
- ms-azuretools.vscode-azurefunctions
- ms-azuretools.vscode-azureresourcegroups
- ms-azuretools.vscode-azurestaticwebapps
- ms-azuretools.vscode-azurestorage
- ms-azuretools.vscode-azurevirtualmachines
- ms-azuretools.vscode-bicep
- ms-azuretools.vscode-containers
- ms-azuretools.vscode-cosmosdb
- ms-azuretools.vscode-docker
- ms-dotnettools.csharp
- ms-dotnettools.vscode-dotnet-runtime
- ms-kubernetes-tools.vscode-kubernetes-tools
- ms-python.black-formatter
- ms-python.debugpy
- ms-python.python
- ms-python.vscode-pylance
- ms-python.vscode-python-envs
- ms-toolsai.datawrangler
- ms-toolsai.jupyter
- ms-toolsai.jupyter-keymap
- ms-toolsai.jupyter-renderers
- ms-toolsai.vscode-ai
- ms-toolsai.vscode-ai-remote
- ms-toolsai.vscode-jupyter-cell-tags
- ms-toolsai.vscode-jupyter-slideshow
- ms-vscode-remote.remote-containers
- ms-vscode-remote.remote-ssh
- ms-vscode-remote.remote-ssh-edit
- ms-vscode-remote.remote-wsl
- ms-vscode-remote.vscode-remote-extensionpack
- ms-vscode.anycode
- ms-vscode.anycode-c-sharp
- ms-vscode.anycode-cpp
- ms-vscode.anycode-go
- ms-vscode.anycode-java
- ms-vscode.anycode-kotlin
- ms-vscode.anycode-php
- ms-vscode.anycode-python
- ms-vscode.anycode-rust
- ms-vscode.anycode-typescript
- ms-vscode.azurecli
- ms-vscode.cmake-tools
- ms-vscode.cpp-devtools
- ms-vscode.cpptools
- ms-vscode.cpptools-extension-pack
- ms-vscode.cpptools-themes
- ms-vscode.hexeditor
- ms-vscode.makefile-tools
- ms-vscode.mono-debug
- ms-vscode.powershell
- ms-vscode.remote-explorer
- ms-vscode.remote-server
- ms-vscode.theme-3024kit
- ms-vscode.theme-markdownkit
- ms-vscode.theme-materialkit
- ms-vscode.vscode-node-azure-pack
- ms-windows-ai-studio.windows-ai-studio
- msazurermtools.azurerm-vscode-tools
- msrvida.vscode-sanddance
- mvllow.rose-pine
- naumovs.color-highlight
- nicholasprieto.morningcoffee
- nilssoderman.batch-runner
- njpwerner.autodocstring
- pixl-garden.bongocat
- pkief.material-icon-theme
- randomfractalsinc.vscode-data-preview
- redhat.vscode-yaml
- remisa.shellman
- richie5um2.vscode-sort-json
- rogalmic.bash-debug
- rooveterinaryinc.roo-cline
- rosshamish.kuskus-kusto-language-server
- rosshamish.kuskus-kusto-syntax-highlighting
- sainnhe.everforest
- samuelcolvin.jinjahtml
- saoudrizwan.claude-dev
- sf-core-ides.blueberry-cider
- shd101wyy.markdown-preview-enhanced
- shortarrow.line-number-deco
- stonec0der.g-dark-theme
- sumitsaha.learn-with-sumit-theme
- swyddfa.esbonio
- syncfusioninc.document-viewer-vscode-extensions
- tamasfe.even-better-toml
- tankashing.blinds-theme
- teabyii.ayu
- teamsdevapp.vscode-ai-foundry
- thakkeross.thakker-light-earth-hc
- thakkeross.thakker-light-mist-hc
- thakkeross.thakker-light-sky-hc
- thang-nm.catppuccin-perfect-icons
- timonwong.shellcheck
- tokyo-night.nvtokyo
- tomoki1207.pdf
- trond-snekvik.simple-rst
- twxs.cmake
- tyriar.sort-lines
- ullissescastro.theme-bracketslight
- uloco.theme-bluloco-dark
- uloco.theme-bluloco-light
- vortizhe.simple-ruby-erb
- vscode-icons-team.vscode-icons
- wangtao0101.debug-leetcode
- wholroyd.jinja
- wraith13.background-phi-colors
- xadillax.viml
- xaviercai.vscode-leetcode-cpp-debug
- yezige.vscode-theme-green-eyecare
- yy0931.vscode-sqlite3-editor
- zaaack.markdown-editor
- zyinmd.sepia
win_background_configs:
  font_name: Space Mono Nerd Font Complete Windows Compatible.ttf
  font_size: 100
  image_dir: .
  image_fraction: 0.25
  output_dir: 02_assets/_outputs_/win_backgrounds
win_backgrounds:
- image: 02_assets/01_green/bogomil-mihaylov-N2sgnKoGbkE-unsplash_crop.jpg
  name: Meeting
- image: 02_assets/01_green/wengang-zhai-YcCcz50xI64-unsplash.jpg
  name: 'Coding '
- image: 02_assets/01_green/shawn-kenessey-gcGYpJzxiqk-unsplash_cropped.jpg
  name: 'Note   '
- image: 02_assets/01_green/shawn-kenessey-gcGYpJzxiqk-unsplash_cropped.jpg
  name: Devbox1
- image: 02_assets/01_green/wengang-zhai-YcCcz50xI64-unsplash.jpg
  name: Devbox2
- image: 02_assets/01_green/wengang-zhai-YcCcz50xI64-unsplash.jpg
  name: 'Learn  '
winget_packages:
- name: Microsoft.VisualStudioCode
  state: null
- name: Canonical.Ubuntu.2204
  state: null
- name: Debian.Debian
  state: null
- name: whitewaterfoundry.fedora-remix-for-wsl
  state: null
- name: Docker.DockerDesktop
  state: null
- name: DominikReichl.KeePass
  state: null
- name: Microsoft.msmpisdk
  state: install
- name: Microsoft.PowerShell
  state: install
- name: Starship.Starship
  state: install
- name: chrisant996.Clink
  state: install
- name: 7zip.7zip
  state: install
- name: cURL.cURL
  state: null
- name: Neovim.Neovim
  state: install
- name: OpenJS.NodeJS
  state: install
- name: dbrgn.tealdeer
  state: install
- name: LLVM.LLVM
  state: install
- name: Google.Chrome
  state: install
- name: DEVCOM.JetBrainsMonoNerdFont
  state: install
- name: Microsoft.PowerToys
  state: install
- name: LutzRoeder.Netron
  state: install
- name: Microsoft.WindowsTerminal
  state: null
- name: Git.Git
  state: null
- name: Obsidian.Obsidian
  state: install
- name: Anaconda.Miniconda3
  state: install
- name: equalsraf.neovim-qt
  state: install
- name: FilesCommunity.Files
  state: install
